#!/bin/bash

# Publish script for HomeworkApp
# This script will:
# 1. Build the project
# 2. Bump version number
# 3. Commit changes
# 4. Push to GitHub (triggering automatic deployment)

set -e  # Exit on any error

echo "🚀 Starting publish process..."

# Check if we're on main branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ]; then
    echo "❌ Error: Must be on main branch to publish. Current branch: $CURRENT_BRANCH"
    exit 1
fi

# Check if working directory is clean
if [ -n "$(git status --porcelain)" ]; then
    echo "❌ Error: Working directory is not clean. Please commit or stash changes first."
    exit 1
fi

echo "✅ Pre-checks passed"

# Build the project
echo "🔨 Building project..."
npm run build
if [ $? -ne 0 ]; then
    echo "❌ Build failed"
    exit 1
fi
echo "✅ Build successful"

# Get current version
CURRENT_VERSION=$(node -p "require('./package.json').version")
echo "📦 Current version: $CURRENT_VERSION"

# Bump version (patch by default)
VERSION_TYPE=${1:-patch}
echo "🔄 Bumping $VERSION_TYPE version..."

npm version $VERSION_TYPE --no-git-tag-version
NEW_VERSION=$(node -p "require('./package.json').version")
echo "📦 New version: $NEW_VERSION"

# Commit changes
echo "📝 Committing version bump and build files..."
git add .
git commit -m "Release v$NEW_VERSION

- Bump version to $NEW_VERSION
- Update build files
- Auto-generated by publish script"

# Create and push tag
echo "🏷️  Creating tag v$NEW_VERSION..."
git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"

# Push to GitHub
echo "📤 Pushing to GitHub..."
git push origin main
git push origin "v$NEW_VERSION"

echo "🎉 Publish complete!"
echo "🌐 Your app will be available at: https://savs-tech.github.io/HomeworkApp/"
echo "📋 GitHub Actions will automatically build and deploy your changes"
